### ISSUE TITLE
could you give a overall example

### ISSUE THREAD

**Issue by scil** [weedsboy/electron-mousehook#1]
e.g.  where  `wnd` and `result` from?  I think the `hookWindowMessage` could receive any type of message, why you create this addon?  I think there must be merit, could you please clarify? 

```
//start MouseHook
const mousehook = require('electron-mousehook')
mousehook.StartMouseHook(wnd)

win.hookWindowMessage(result, async (wParam, lParam) => {
    const event = wParam.readUInt32LE(0)
    if (event == 0x0200 || event == 0x00a0) {
        console.log('mouse move')
    } else if (event == 0x0201 || event == 0x00a1) {
        console.log('L down')
    } else if (event == 0x0202 || event == 0x00a2) {
        console.log('L up')
    }
})

//stop MouseHook
mousehook.StopMouseHook(wnd)
```

**Comment by weedsboy** [comment]
**hookWindowMessage** can only receive window message,but not system message. So i create this addon.

**wnd** is your window handle.
**result** is **StartMouseHook** result.

```
const result = mousehook.StartMouseHook(wnd)
if (result == 0) {
      console.log('startMouseHook Error.')
      return
    }
```

**Comment by scil** [comment]
I see. Thank you very much. I think this statment `hookWindowMessage can only receive window message` is very important!
